<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-E57MT6J" failures="1" tests="9" name="tests.Summer_DressesTest" time="74.045" errors="0" timestamp="2020-04-03T19:09:49 CEST" skipped="4">
  <testcase classname="tests.Summer_DressesTest" name="test05_logInBack" time="8.827">
    <failure message="The following asserts failed:
	expected [2] but found [(empty)]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [2] but found [(empty)]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at tests.Summer_DressesTest.test05_logInBack(Summer_DressesTest.java:125)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test05_logInBack -->
  <system-out/>
  <testcase classname="tests.Summer_DressesTest" name="test01_clickFirst" time="8.147"/>
  <system-out/>
  <testcase classname="tests.Summer_DressesTest" name="test02_Order" time="4.417"/>
  <system-out/>
  <testcase classname="tests.Summer_DressesTest" name="test04_registration" time="42.255"/>
  <system-out/>
  <testcase classname="tests.Summer_DressesTest" name="test03_Values" time="10.399"/>
  <system-out/>
  <testcase classname="tests.Summer_DressesTest" name="test04_Qty">
    <skipped/>
  </testcase> <!-- test04_Qty -->
  <system-out/>
  <testcase classname="tests.Summer_DressesTest" name="test06_proceedBtn">
    <skipped/>
  </testcase> <!-- test06_proceedBtn -->
  <system-out/>
  <testcase classname="tests.Summer_DressesTest" name="test04_register">
    <skipped/>
  </testcase> <!-- test04_register -->
  <system-out/>
  <testcase classname="tests.Summer_DressesTest" name="test05_Title">
    <skipped/>
  </testcase> <!-- test05_Title -->
  <system-out/>
</testsuite> <!-- tests.Summer_DressesTest -->
